version: '3.8'

services:
  musicplayer-api:
    container_name: music-player-service
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '8381:8080'
    volumes:
      - ./src/MusicPlayer.Api/Media:/app/Media
    environment:
      - ASPNETCORE_ENVIRONMENT=Production